apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devs-service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devs-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: devs-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: devs-frontend
